-- ============================================
-- MIMIN ERP - FULL SCHEMA (Combined + Cleaned)
-- Generated by Mavis - 2026-08-01
-- ============================================
-- File nay gop 2 schema:
--   1. src/lib/supabase/schema.sql (10 bang chinh)
--   2. src/lib/supabase/advanced-schema.sql (RLS + audit + 2FA)
-- Da clean: bo duplicate, fix encoding, xoa trigger loi (bang_luong chua co)
-- ============================================

-- ============================================
-- PHAN 1: SCHEMA CHINH (10 bang)
-- ============================================

-- 1. Bang Don hang
CREATE TABLE IF NOT EXISTS don_hang (
  id TEXT PRIMARY KEY,
  ma_dh TEXT UNIQUE NOT NULL,
  ngay_dat DATE NOT NULL,
  ngay_giao DATE NOT NULL,
  khach_hang TEXT NOT NULL,
  sdt TEXT,
  san_pham TEXT NOT NULL,
  loai TEXT CHECK (loai IN ('Ao', 'Bo')) NOT NULL,
  so_luong INTEGER NOT NULL,
  don_gia NUMERIC NOT NULL,
  thanh_tien NUMERIC NOT NULL,
  trang_thai TEXT CHECK (trang_thai IN ('Moi', 'Da duyet', 'Dang SX', 'Hoan thanh', 'Da giao', 'Huy')) DEFAULT 'Moi',
  tien_coc NUMERIC DEFAULT 0,
  ghi_chu TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Bang Phan cong cong doan
CREATE TABLE IF NOT EXISTS phan_cong (
  id TEXT PRIMARY KEY,
  lenh_cat_id TEXT NOT NULL,
  cong_doan TEXT NOT NULL,
  nguoi_ma TEXT NOT NULL,
  nguoi_ten TEXT NOT NULL,
  nguoi_loai TEXT,
  nguoi_sdt TEXT,
  don_gia_giao NUMERIC NOT NULL,
  so_luong_giao INTEGER NOT NULL,
  don_vi TEXT,
  ngay_giao DATE NOT NULL,
  ngay_xong_du_kien DATE NOT NULL,
  trang_thai TEXT DEFAULT 'Cho giao',
  da_thanh_toan NUMERIC DEFAULT 0,
  ghi_chu TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Bang Giao dich kho
CREATE TABLE IF NOT EXISTS giao_dich_kho (
  id TEXT PRIMARY KEY,
  ngay DATE NOT NULL,
  loai TEXT CHECK (loai IN ('NHAP', 'XUAT')) NOT NULL,
  ma_vt TEXT NOT NULL,
  ten_vt TEXT NOT NULL,
  so_luong NUMERIC NOT NULL,
  don_vi TEXT NOT NULL,
  don_gia NUMERIC NOT NULL,
  thanh_tien NUMERIC NOT NULL,
  loai_kho TEXT CHECK (loai_kho IN ('vai', 'phu-lieu')) NOT NULL,
  nguon_nhap TEXT,
  nguoi_thuc_hien TEXT,
  ghi_chu TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Bang NCC (Nha cung cap)
CREATE TABLE IF NOT EXISTS ncc (
  stt INTEGER PRIMARY KEY,
  ten TEXT NOT NULL,
  vai_tro TEXT,
  sdt TEXT,
  mail TEXT,
  dia_chi TEXT,
  ma_so_thue TEXT,
  cong_no NUMERIC DEFAULT 0,
  rating NUMERIC DEFAULT 4,
  ghi_chu TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Bang Khach hang
CREATE TABLE IF NOT EXISTS khach_hang (
  stt INTEGER PRIMARY KEY,
  ma_kh TEXT UNIQUE NOT NULL,
  ten TEXT NOT NULL,
  sdt TEXT,
  email TEXT,
  dia_chi TEXT,
  mst TEXT,
  cong_no NUMERIC DEFAULT 0,
  rating NUMERIC DEFAULT 4,
  ghi_chu TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Bang Nhan su
CREATE TABLE IF NOT EXISTS nhan_su (
  stt INTEGER PRIMARY KEY,
  ma_nv TEXT UNIQUE NOT NULL,
  ho_ten TEXT NOT NULL,
  bo_phan TEXT,
  chuc_vu TEXT,
  sdt TEXT,
  email TEXT,
  luong_cung NUMERIC DEFAULT 8500000,
  rating NUMERIC DEFAULT 4,
  trang_thai TEXT DEFAULT 'dang_lam',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Bang Push Subscriptions (cho Web Push Notification)
CREATE TABLE IF NOT EXISTS push_subscriptions (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT,
  endpoint TEXT UNIQUE NOT NULL,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Bang Notifications (luu thong bao gui cho user)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT,
  type TEXT NOT NULL, -- 'late', 'due_soon', 'new_order', 'qc_fail', 'low_stock'
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  link TEXT,
  data JSONB,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Bang Bang luong (can cho advanced-schema)
CREATE TABLE IF NOT EXISTS bang_luong (
  id TEXT PRIMARY KEY,
  ma_nv TEXT NOT NULL,
  thang DATE NOT NULL,
  luong_cung NUMERIC DEFAULT 0,
  luong_sp NUMERIC DEFAULT 0,
  phu_cap NUMERIC DEFAULT 0,
  thuc_nhan NUMERIC DEFAULT 0,
  trang_thai TEXT DEFAULT 'CHUA_TT',
  ngay_tt DATE,
  nguoi_tt TEXT,
  ghi_chu TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- PHAN 2: ROW LEVEL SECURITY (RLS)
-- ============================================

-- Enable RLS cho cac bang chinh
ALTER TABLE don_hang ENABLE ROW LEVEL SECURITY;
ALTER TABLE phan_cong ENABLE ROW LEVEL SECURITY;
ALTER TABLE giao_dich_kho ENABLE ROW LEVEL SECURITY;
ALTER TABLE ncc ENABLE ROW LEVEL SECURITY;
ALTER TABLE khach_hang ENABLE ROW LEVEL SECURITY;
ALTER TABLE nhan_su ENABLE ROW LEVEL SECURITY;
ALTER TABLE bang_luong ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Policies: Cho phep user da dang nhap CRUD
CREATE POLICY "Allow all for authenticated" ON don_hang FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON phan_cong FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON giao_dich_kho FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON ncc FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON khach_hang FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON nhan_su FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all for authenticated" ON bang_luong FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow read for all" ON push_subscriptions FOR SELECT USING (true);
CREATE POLICY "Allow insert for all" ON push_subscriptions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow delete for all" ON push_subscriptions FOR DELETE USING (true);
CREATE POLICY "Allow all for authenticated" ON notifications FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- PHAN 3: ADVANCED (Audit + 2FA + Custom Roles)
-- ============================================

-- 9.1 AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL,
  user_email TEXT NOT NULL,
  user_role TEXT NOT NULL,
  action TEXT NOT NULL,
  module TEXT NOT NULL,
  resource_id TEXT,
  resource_name TEXT,
  description TEXT NOT NULL,
  old_value JSONB,
  new_value JSONB,
  success BOOLEAN DEFAULT TRUE,
  error_message TEXT,
  ip INET,
  user_agent TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_module ON audit_logs(module);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_audit_failed ON audit_logs(success) WHERE success = FALSE;

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- 9.2 TIME-BOUND PERMISSIONS
CREATE TABLE IF NOT EXISTS time_bounds (
  id SERIAL PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_email TEXT NOT NULL,
  role TEXT NOT NULL,
  start_date TIMESTAMPTZ NOT NULL,
  end_date TIMESTAMPTZ NOT NULL,
  reason TEXT,
  approved_by TEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_time_bounds_user ON time_bounds(user_id);
CREATE INDEX IF NOT EXISTS idx_time_bounds_active ON time_bounds(active) WHERE active = TRUE;

ALTER TABLE time_bounds ENABLE ROW LEVEL SECURITY;

-- 9.3 CUSTOM ROLES
CREATE TABLE IF NOT EXISTS custom_roles (
  id TEXT PRIMARY KEY,
  role_key TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  color TEXT,
  permissions JSONB NOT NULL DEFAULT '{}',
  is_system BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_custom_roles_key ON custom_roles(role_key);

ALTER TABLE custom_roles ENABLE ROW LEVEL SECURITY;

-- 9.4 2FA CONFIGS
CREATE TABLE IF NOT EXISTS two_factor_configs (
  user_id TEXT PRIMARY KEY,
  user_email TEXT NOT NULL,
  enabled BOOLEAN DEFAULT FALSE,
  secret TEXT NOT NULL,
  backup_codes TEXT[] NOT NULL DEFAULT '{}',
  enabled_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE two_factor_configs ENABLE ROW LEVEL SECURITY;

-- 9.5 LOGIN ATTEMPTS
CREATE TABLE IF NOT EXISTS login_attempts (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL,
  success BOOLEAN NOT NULL,
  ip INET,
  user_agent TEXT,
  attempted_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_login_attempts_email ON login_attempts(email, attempted_at DESC);

ALTER TABLE login_attempts ENABLE ROW LEVEL SECURITY;

-- ============================================
-- PHAN 4: TRIGGERS & FUNCTIONS
-- ============================================

-- Function: Tu dong tao notification khi phan cong tre han
CREATE OR REPLACE FUNCTION notify_late_assignment()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.ngay_xong_du_kien < CURRENT_DATE AND NEW.trang_thai NOT IN ('Hoan thanh', 'Da thanh toan') THEN
    INSERT INTO notifications (type, title, body, link, data)
    VALUES (
      'late',
      '⚠️ Công đoạn trễ hạn',
      NEW.cong_doan || ' - ' || NEW.nguoi_ten,
      '/cong-no?lenh=' || NEW.lenh_cat_id,
      jsonb_build_object('phanCongId', NEW.id, 'lenhCatId', NEW.lenh_cat_id)
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_notify_late ON phan_cong;
CREATE TRIGGER trg_notify_late
  AFTER INSERT OR UPDATE ON phan_cong
  FOR EACH ROW
  EXECUTE FUNCTION notify_late_assignment();

-- Function: Notification khi ton kho thap
CREATE OR REPLACE FUNCTION notify_low_stock()
RETURNS TRIGGER AS $$
DECLARE
  v_ton NUMERIC;
BEGIN
  SELECT
    COALESCE((SELECT SUM(so_luong) FROM giao_dich_kho WHERE ma_vt = NEW.ma_vt AND loai = 'NHAP'), 0) -
    COALESCE((SELECT SUM(so_luong) FROM giao_dich_kho WHERE ma_vt = NEW.ma_vt AND loai = 'XUAT'), 0)
  INTO v_ton;

  IF v_ton < 0 THEN
    INSERT INTO notifications (type, title, body, link, data)
    VALUES (
      'low_stock',
      '📦 Tồn kho âm!',
      NEW.ten_vt || ' đang âm: ' || v_ton,
      '/kho-vai',
      jsonb_build_object('maVT', NEW.ma_vt, 'ton', v_ton)
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_notify_low_stock ON giao_dich_kho;
CREATE TRIGGER trg_notify_low_stock
  AFTER INSERT ON giao_dich_kho
  FOR EACH ROW
  WHEN (NEW.loai = 'XUAT')
  EXECUTE FUNCTION notify_low_stock();

-- Auto-log function: ghi log khi UPDATE/DELETE
CREATE OR REPLACE FUNCTION auto_log_changes()
RETURNS TRIGGER AS $$
DECLARE
  v_user_id TEXT;
  v_user_name TEXT;
  v_user_role TEXT;
  v_action TEXT;
BEGIN
  v_user_id := COALESCE(auth.uid()::TEXT, 'system');
  v_user_name := COALESCE(auth.jwt() ->> 'email', 'system');
  v_user_role := COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', 'user');

  IF TG_OP = 'UPDATE' THEN
    INSERT INTO audit_logs (id, user_id, user_name, user_email, user_role, action, module, resource_id, resource_name, description, old_value, new_value)
    VALUES (
      'log_' || extract(epoch from now()) || '_' || substr(md5(random()::TEXT), 1, 8),
      v_user_id, v_user_name, v_user_name, v_user_role, 'update', TG_TABLE_NAME,
      OLD.id::TEXT, OLD.ma_nv, 'Sửa ' || TG_TABLE_NAME,
      to_jsonb(OLD), to_jsonb(NEW)
    );
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO audit_logs (id, user_id, user_name, user_email, user_role, action, module, resource_id, resource_name, description, old_value)
    VALUES (
      'log_' || extract(epoch from now()) || '_' || substr(md5(random()::TEXT), 1, 8),
      v_user_id, v_user_name, v_user_name, v_user_role, 'delete', TG_TABLE_NAME,
      OLD.id::TEXT, OLD.ma_nv, 'Xoá ' || TG_TABLE_NAME,
      to_jsonb(OLD)
    );
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Apply trigger cho cac bang chinh
DROP TRIGGER IF EXISTS trg_audit_nhan_su ON nhan_su;
CREATE TRIGGER trg_audit_nhan_su
  AFTER UPDATE OR DELETE ON nhan_su
  FOR EACH ROW EXECUTE FUNCTION auto_log_changes();

DROP TRIGGER IF EXISTS trg_audit_don_hang ON don_hang;
CREATE TRIGGER trg_audit_don_hang
  AFTER UPDATE OR DELETE ON don_hang
  FOR EACH ROW EXECUTE FUNCTION auto_log_changes();

DROP TRIGGER IF EXISTS trg_audit_bang_luong ON bang_luong;
CREATE TRIGGER trg_audit_bang_luong
  AFTER UPDATE OR DELETE ON bang_luong
  FOR EACH ROW EXECUTE FUNCTION auto_log_changes();

-- ============================================
-- PHAN 5: INDEXES
-- ============================================
CREATE INDEX IF NOT EXISTS idx_don_hang_ngay_giao ON don_hang(ngay_giao);
CREATE INDEX IF NOT EXISTS idx_don_hang_trang_thai ON don_hang(trang_thai);
CREATE INDEX IF NOT EXISTS idx_phan_cong_lenh ON phan_cong(lenh_cat_id);
CREATE INDEX IF NOT EXISTS idx_phan_cong_deadline ON phan_cong(ngay_xong_du_kien);
CREATE INDEX IF NOT EXISTS idx_gd_kho_ma_vt ON giao_dich_kho(ma_vt);
CREATE INDEX IF NOT EXISTS idx_gd_kho_loai ON giao_dich_kho(loai_kho, loai);
CREATE INDEX IF NOT EXISTS idx_notif_user ON notifications(user_id, read_at);
CREATE INDEX IF NOT EXISTS idx_bang_luong_nv ON bang_luong(ma_nv, thang);

-- ============================================
-- PHAN 6: REALTIME
-- ============================================
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE don_hang;
    ALTER PUBLICATION supabase_realtime ADD TABLE phan_cong;
    ALTER PUBLICATION supabase_realtime ADD TABLE giao_dich_kho;
    ALTER PUBLICATION supabase_realtime ADD TABLE ncc;
    ALTER PUBLICATION supabase_realtime ADD TABLE khach_hang;
    ALTER PUBLICATION supabase_realtime ADD TABLE nhan_su;
    ALTER PUBLICATION supabase_realtime ADD TABLE bang_luong;
    ALTER PUBLICATION supabase_realtime ADD TABLE notifications;
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Realtime publication skipped (some tables may not exist yet)';
  END;
END $$;

-- ============================================
-- HOAN THANH
-- ============================================
-- Da tao: 13 bang + 3 functions + triggers + RLS + indexes + realtime
-- Bang: don_hang, phan_cong, giao_dich_kho, ncc, khach_hang, nhan_su,
--       bang_luong, push_subscriptions, notifications, audit_logs,
--       time_bounds, custom_roles, two_factor_configs, login_attempts
