call npm run test:brave
call npm run test:dr0
call npm run test:dr1
call npm run test:dr2
call npm run test:dr3
call npm run test:dr4
call npm run test:dr5
call npm run test:dr6
call npm run test:dr7
call npm run test:dr8
call npm run test:dr9
call npx tsc --noEmit
call npm run build
