"use client";

import { useMemo, useState } from "react";
import { Edit2, ListPlus, PackageSearch, Plus, Tag, Trash2 } from "lucide-react";
import { CrudModal, type FieldDef } from "@/components/ui/CrudModal";
import { useDanhMucSP } from "@/lib/data/danh-muc-sp-store";
import { KENH_BAN, type BangGia, type BangGiaChiTiet, type KenhBan, type TrangThaiBangGia, useBangGia } from "@/lib/data/bang-gia-store";

const CHANNEL_LABELS: Record<KenhBan, string> = { "ban-le": "Bán lẻ", "ban-si": "Bán sỉ", "ban-lo": "Bán lô", tiktok: "TikTok Shop", shopee: "Shopee" };
const STATUS_LABELS: Record<TrangThaiBangGia, string> = { nhap: "Bản nháp", "dang-ap-dung": "Đang áp dụng", "ngung-ap-dung": "Ngừng áp dụng" };
const STATUS_STYLES: Record<TrangThaiBangGia, string> = { nhap: "bg-slate-100 text-slate-600", "dang-ap-dung": "bg-emerald-50 text-emerald-700", "ngung-ap-dung": "bg-rose-50 text-rose-700" };

const formatVND = (value: number) => new Intl.NumberFormat("vi-VN", { style: "currency", currency: "VND", maximumFractionDigits: 0 }).format(value);
const rangesOverlap = (fromA: number, toA: number | undefined, fromB: number, toB: number | undefined) => fromA <= (toB ?? Infinity) && fromB <= (toA ?? Infinity);

export default function BangGiaPage() {
  const { bangGia, chiTiet, loading, themBangGia, suaBangGia, xoaBangGia, themChiTiet, suaChiTiet, xoaChiTiet } = useBangGia();
  const { dsSanPham, loading: loadingProducts } = useDanhMucSP();
  const [showListForm, setShowListForm] = useState(false);
  const [editingList, setEditingList] = useState<BangGia | null>(null);
  const [detailListId, setDetailListId] = useState<string | null>(null);
  const [showDetailForm, setShowDetailForm] = useState(false);
  const [editingDetail, setEditingDetail] = useState<BangGiaChiTiet | null>(null);
  const [previewImage, setPreviewImage] = useState<string | null>(null);

  const selectedList = bangGia.find((item) => item.id === detailListId) || null;
  const selectedDetails = useMemo(() => chiTiet.filter((item) => item.bangGiaId === detailListId).sort((a, b) => a.maSP.localeCompare(b.maSP) || (a.maSKUBienThe || "").localeCompare(b.maSKUBienThe || "") || a.soLuongTu - b.soLuongTu), [chiTiet, detailListId]);
  const productsById = useMemo(() => new Map(dsSanPham.map((product) => [product.id, product])), [dsSanPham]);
  const productOptions = useMemo(() => [...dsSanPham].sort((a, b) => a.id.localeCompare(b.id)).map((product) => ({ value: product.id, label: `${product.id} — ${product.tenSP}` })), [dsSanPham]);

  const listInitial: Record<string, string> = editingList ? { tenBangGia: editingList.tenBangGia, kenhBan: editingList.kenhBan, tuNgay: editingList.tuNgay || "", denNgay: editingList.denNgay || "", trangThai: editingList.trangThai, ghiChu: editingList.ghiChu || "" } : { tenBangGia: "", kenhBan: "ban-le", tuNgay: "", denNgay: "", trangThai: "nhap", ghiChu: "" };
  const detailInitial: Record<string, string> = editingDetail ? { maSP: editingDetail.maSP, maSKUBienThe: editingDetail.maSKUBienThe || "", giaBan: String(editingDetail.giaBan), soLuongTu: String(editingDetail.soLuongTu), soLuongDen: editingDetail.soLuongDen == null ? "" : String(editingDetail.soLuongDen), ghiChu: editingDetail.ghiChu || "" } : { maSP: "", maSKUBienThe: "", giaBan: "", soLuongTu: "1", soLuongDen: "", ghiChu: "" };

  const listFields: FieldDef[] = [
    { name: "tenBangGia", label: "Tên bảng giá", type: "text", required: true, placeholder: "VD: Giá bán sỉ tháng 09/2026" },
    { name: "kenhBan", label: "Kênh bán", type: "select", required: true, options: KENH_BAN.map((channel) => ({ value: channel, label: CHANNEL_LABELS[channel] })) },
    { name: "tuNgay", label: "Từ ngày", type: "date" }, { name: "denNgay", label: "Đến ngày", type: "date" },
    { name: "trangThai", label: "Trạng thái", type: "select", required: true, options: Object.entries(STATUS_LABELS).map(([value, label]) => ({ value, label })) },
    { name: "ghiChu", label: "Ghi chú", type: "textarea" },
  ];
  const detailFields: FieldDef[] = [
    { name: "maSP", label: "Sản phẩm trong danh mục", type: "select", required: true, options: productOptions, emptyLabel: loadingProducts ? "Đang tải danh mục..." : "-- Chọn sản phẩm --", clearOnChange: ["maSKUBienThe"] },
    { name: "maSKUBienThe", label: "Biến thể / SKU", type: "select", disabled: (values) => !values.maSP, emptyLabel: "Tất cả biến thể", options: (values) => productsById.get(values.maSP)?.dsMau.filter((variant) => variant.maSKU?.trim()).map((variant) => ({ value: variant.maSKU.trim(), label: `${variant.ten} — ${variant.maSKU.trim()}` })) || [] },
    { name: "giaBan", label: "Giá bán (VNĐ)", type: "number", min: 1, step: 1, required: true, placeholder: "VD: 150000" },
    { name: "soLuongTu", label: "Số lượng từ", type: "number", min: 1, step: 1, required: true },
    { name: "soLuongDen", label: "Số lượng đến (để trống nếu không giới hạn)", type: "number", min: 1, step: 1 },
    { name: "ghiChu", label: "Ghi chú", type: "textarea" },
  ];

  return <div className="space-y-5 animate-fade-in">
    <section className="rounded-3xl bg-gradient-to-r from-amber-500 to-orange-600 p-6 text-white shadow-xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-semibold"><Tag className="h-4 w-4" /> MIMIN ERP · Bán hàng</p><h1 className="mt-2 text-3xl font-black md:text-4xl">Bảng giá bán</h1><p className="mt-2 text-sm">Thiết lập giá theo đúng sản phẩm, SKU biến thể, kênh bán và ngưỡng số lượng.</p></div><button onClick={() => { setEditingList(null); setShowListForm(true); }} className="flex items-center gap-2 rounded-xl border border-white/30 bg-white/20 px-4 py-3 font-bold hover:bg-white/30"><Plus className="h-5 w-5" /> Tạo bảng giá</button></div></section>

    {loading ? <section className="card p-12 text-center text-slate-500">Đang tải bảng giá...</section> : bangGia.length === 0 ? <section className="card p-12 text-center text-slate-500"><Tag className="mx-auto mb-3 h-10 w-10 opacity-30" /><p className="font-bold">Chưa có bảng giá</p><p className="mt-1 text-sm">Tạo bảng giá đầu tiên cho từng kênh bán.</p></section> : <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{bangGia.map((item) => { const count = chiTiet.filter((detail) => detail.bangGiaId === item.id).length; return <article key={item.id} className="card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-amber-600">{CHANNEL_LABELS[item.kenhBan]}</p><h2 className="mt-1 text-lg font-black text-slate-900 dark:text-white">{item.tenBangGia}</h2></div><span className={`rounded-full px-2 py-1 text-xs font-bold ${STATUS_STYLES[item.trangThai]}`}>{STATUS_LABELS[item.trangThai]}</span></div><div className="my-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-800/60"><div><p className="text-slate-400">Thời hạn</p><b>{item.tuNgay || "Không giới hạn"} {item.denNgay ? `→ ${item.denNgay}` : ""}</b></div><div><p className="text-slate-400">Mức giá</p><b>{count} dòng</b></div></div><div className="flex gap-2"><button onClick={() => setDetailListId(item.id)} className="flex flex-1 items-center justify-center gap-1 rounded-lg bg-amber-500 py-2 text-xs font-bold text-white"><ListPlus className="h-3 w-3" /> Chi tiết giá</button><button onClick={() => { setEditingList(item); setShowListForm(true); }} className="rounded-lg bg-slate-100 px-3 py-2 text-slate-600" title="Sửa"><Edit2 className="h-4 w-4" /></button><button onClick={() => { if (confirm(`Xóa bảng giá ${item.tenBangGia}?`)) void xoaBangGia(item.id); }} className="rounded-lg bg-red-50 px-3 py-2 text-red-700" title="Xóa"><Trash2 className="h-4 w-4" /></button></div></article>; })}</section>}

    <CrudModal open={showListForm} onClose={() => setShowListForm(false)} title={editingList ? "Sửa bảng giá" : "Tạo bảng giá"} fields={listFields} initial={listInitial} onSubmit={async (values) => { const tenBangGia = values.tenBangGia.trim(); if (values.tuNgay && values.denNgay && values.denNgay < values.tuNgay) throw new Error("Đến ngày phải bằng hoặc sau Từ ngày."); if (bangGia.some((item) => item.id !== editingList?.id && item.tenBangGia.trim().toLocaleLowerCase("vi") === tenBangGia.toLocaleLowerCase("vi") && item.kenhBan === values.kenhBan)) throw new Error("Tên bảng giá đã tồn tại trong kênh bán này."); const data = { tenBangGia, kenhBan: values.kenhBan as KenhBan, tuNgay: values.tuNgay || undefined, denNgay: values.denNgay || undefined, trangThai: values.trangThai as TrangThaiBangGia, ghiChu: values.ghiChu?.trim() || undefined }; if (editingList) await suaBangGia(editingList.id, data); else await themBangGia(data); }} />

    {selectedList && <div className="fixed inset-0 z-[60] flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/40" onClick={() => setDetailListId(null)} /><div className="relative card max-h-[90vh] w-full max-w-5xl overflow-y-auto p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-sm font-bold text-amber-600">{CHANNEL_LABELS[selectedList.kenhBan]}</p><h2 className="text-xl font-black">{selectedList.tenBangGia}</h2></div><button onClick={() => setDetailListId(null)} className="btn-secondary">Đóng</button></div>
      {selectedDetails.length === 0 ? <div className="mb-4 rounded-2xl border border-dashed border-slate-300 p-8 text-center text-slate-500"><PackageSearch className="mx-auto mb-2 h-9 w-9 opacity-40" /><p className="font-bold">Chưa có dòng giá</p><p className="text-sm">Chọn sản phẩm từ danh mục để bắt đầu thiết lập.</p></div> : <div className="mb-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500"><th className="p-2 w-14 text-center">Hình ảnh</th><th className="p-2">Sản phẩm</th><th className="p-2">Biến thể / SKU</th><th className="p-2">Số lượng</th><th className="p-2">Giá bán</th><th className="p-2" /></tr></thead><tbody>{selectedDetails.map((detail) => { const product = productsById.get(detail.maSP); const variant = product?.dsMau.find((item) => item.maSKU === detail.maSKUBienThe); const imgUrl = variant?.img || product?.hinhAnh || ""; return <tr key={detail.id} className="border-b"><td className="p-2 text-center">{imgUrl ? <img src={imgUrl} alt="Thumb" onClick={() => setPreviewImage(imgUrl)} className="inline-block h-10 w-10 min-w-10 rounded-md object-cover border border-slate-200 shadow-sm hover:scale-110 transition-transform cursor-zoom-in" title="Nhấn để phóng lớn" /> : <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-md border border-slate-100 bg-slate-50 text-slate-300"><Tag className="h-4 w-4" /></div>}</td><td className="p-2"><b>{detail.maSP}</b><p className="text-xs text-slate-500">{product?.tenSP || "Sản phẩm không còn trong danh mục"}</p></td><td className="p-2">{detail.maSKUBienThe ? <><b>{variant?.ten || "SKU"}</b><p className="text-xs text-slate-500">{detail.maSKUBienThe}</p></> : "Tất cả biến thể"}</td><td className="p-2">{detail.soLuongTu} {detail.soLuongDen ? `– ${detail.soLuongDen}` : "+"}</td><td className="p-2 font-bold text-emerald-600">{formatVND(detail.giaBan)}</td><td className="p-2 text-right whitespace-nowrap"><button onClick={() => { setEditingDetail(detail); setShowDetailForm(true); }} className="mr-3 text-amber-600">Sửa</button><button onClick={() => { if (confirm("Xóa dòng giá này?")) void xoaChiTiet(detail.id); }} className="text-red-600">Xóa</button></td></tr>; })}</tbody></table></div>}
      <button onClick={() => { setEditingDetail(null); setShowDetailForm(true); }} disabled={loadingProducts || dsSanPham.length === 0} className="btn-primary inline-flex items-center gap-2 disabled:cursor-not-allowed disabled:opacity-50"><Plus className="h-4 w-4" /> Thêm dòng giá</button>{!loadingProducts && dsSanPham.length === 0 && <p className="mt-2 text-sm text-rose-600">Danh mục sản phẩm đang trống. Cần tạo sản phẩm trước khi thiết lập giá.</p>}
      <CrudModal open={showDetailForm} onClose={() => setShowDetailForm(false)} title={editingDetail ? "Sửa dòng giá" : "Thêm dòng giá"} fields={detailFields} initial={detailInitial} onSubmit={async (values) => { const product = productsById.get(values.maSP); if (!product) throw new Error("Sản phẩm không tồn tại trong danh mục."); const sku = values.maSKUBienThe || undefined; if (sku && !product.dsMau.some((variant) => variant.maSKU === sku)) throw new Error("SKU không thuộc sản phẩm đã chọn."); const giaBan = Number(values.giaBan); const soLuongTu = Number(values.soLuongTu); const soLuongDen = values.soLuongDen ? Number(values.soLuongDen) : undefined; if (!Number.isFinite(giaBan) || giaBan <= 0) throw new Error("Giá bán phải lớn hơn 0."); if (!Number.isInteger(soLuongTu) || soLuongTu < 1 || (soLuongDen !== undefined && (!Number.isInteger(soLuongDen) || soLuongDen < soLuongTu))) throw new Error("Khoảng số lượng không hợp lệ."); if (selectedDetails.some((item) => item.id !== editingDetail?.id && item.maSP === product.id && (item.maSKUBienThe || undefined) === sku && rangesOverlap(soLuongTu, soLuongDen, item.soLuongTu, item.soLuongDen))) throw new Error("Khoảng số lượng bị trùng với một dòng giá của cùng sản phẩm và biến thể."); const data = { bangGiaId: selectedList.id, maSP: product.id, maSKUBienThe: sku, giaBan, soLuongTu, soLuongDen, ghiChu: values.ghiChu?.trim() || undefined }; if (editingDetail) await suaChiTiet(editingDetail.id, data); else await themChiTiet(data); }} />
    </div></div>}
    {previewImage && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 p-4 animate-fade-in cursor-zoom-out" onClick={() => setPreviewImage(null)}><img src={previewImage} alt="Preview" className="max-h-[90vh] max-w-full rounded-lg object-contain shadow-2xl" /></div>}
  </div>;
}
